
export const FIREBASE_DEFINITIONS_REQUEST: string = "FIREBASE_DEFINITIONS_REQUEST";
export const FIREBASE_DEFINITIONS_SUCCESS: string = "FIREBASE_DEFINITIONS_SUCCESS";
export const FIREBASE_DEFINITIONS_ERROR: string = "FIREBASE_DEFINITIONS_ERROR";

export const REFERENCES_INIT: string = "REFERENCES_INIT"
export const REFERENCES_FINISHED: string = "REFERENCES_FINISHED"